### ISSUE TITLE
Implement infrastructure to evaluate the MCA topology using IPv6 extension headers/IPv4 options

### ISSUE THREAD

**Issue by luizbarcelos** [TopologyMapping/mca#14]
The `mca` package currently runs MDA/MCA using the `run` method of the `MCA` class with the arguments provided by the user. Among the outputs of the run, there is the discovered topology generated when traversing each TTL, which is an instance of the `Topology` class.

The task at hand is to implement the `run_extended_classification` method inside the `MCA` class, which is an **additional classification step to check whether load balancers follow the IPv6 next-header chain or correctly parse IPv4 options**. The goal is to assess whether the **new set of probes** will reach the same `answer_ip` as the original ones, considering the **desired level of confidence**.

Nodes in the topology that were previously marked as `per-packet` during the MCA run should be ignored by this new feature.

After running `MDA/MCA`, the topology object has the discovered nodes for each `TTL`. In addition, the flow identifiers used during the discovery process can be accessed by the `get_discovery_flow_ids` method of the `Identifier` class, providing the `TTL` and the `answer_ip`. Both objects are members of the `MCA` class. 

In order to modify the `Forge` object of each `Probe` to take extension headers/options into account without breaking the MCA probing scheme, there should be a new argument to the `__init__` of the `Probe` class called `chaining_test` (`bool`). Care must be taken so that the parsing of the replies is also updated to consider IPv6 extension headers and IPv4 options (the flow identifier may change in the encapsulated headers);

For each node in the topology that was not classified as `per-packet`, resend the modified versions of each probe a given number of times, according to the desired level of confidence, and compare their `answer_ip`s with the original probe used in the MCA run. The classification must be stopped the first time the algorithm finds a `answer_ip` for one of the new probes that does not match the `answer_ip` of the original probe.

**Comment by cunha** [comment]
Put in other words, we'll add an additional classification step to check whether load balancers follow the IPv6 next-header chain or correctly parse IPv4 options.

In 2, care must be taken so that the parsing of the replies is also updated to consider IPv6 extension headers and IPv4 options (the flow identifier may change in the encapsulated headers).

For 3, we can stop the classification early as soon as we see a response that does not match `answer_ip`, and would need to send a fixed number of packets (and receive responses from `answer_ip`) to get the desired level of confidence.

**Comment by luizbarcelos** [comment]
Thanks, @cunha, I'll update the description. I wanted to use our meeting today to discuss/dig deeper in those steps, making sure my understanding is more concrete so we can proceed with the implementation. Feel free to edit/update the description as needed so we have everything regarding this implementation well documented, thus avoiding future misunderstandings/misconceptions/reworks.
