### ISSUE TITLE
Create array with high-entropy random values to use in packets

### ISSUE THREAD

**Issue by cunha** [TopologyMapping/mca#3]
It seems the current code sends small `int` values on packets as flow IDs. We should create a list with high-entropy, random constants in the code and take the values sent on packets from this list (we could, e.g., index the list with the flow ID).

A single list with 256 entries and 16-bit values should work, as Scapy (seems to) do a binary `and` to take the least-significant bits if fields have less than 16 bits.

**Comment by luizbarcelos** [comment]
Reassigned this issue to @cunha since he will generate the gold list of 256 16-bits flow identifiers using an existing functionality implemented in Rust. Ítalo, let me know if you need any help.
